tables:
  - name: persons
    count: 10
    columns:
      - name: id
        type: cuid2
        processor:
          length: 14
      - name: name
        type: gen
        processor:
          template: '{{FirstName}} {{LastName}}'
      - name: email
        type: gen
        processor:
          template: '{{Email}}'
      - name: cpf
        type: gen
        processor:
          template: '{{CPF}}'
      - name: cpnjf
        type: gen
        processor:
          template: '{{CNPJ}}'
      - name: cpf2
        type: gen
        processor:
          value: ${cpf}
      - name: cnpj2
        type: gen
        processor:
          value: ${cnpj}