- table: person
  count: 10000
  columns:
    - name: id
      type: gen
      processor:
        value: ${uuid}
    - name: full_name
      type: gen
      processor:
        value: ${first_name} ${last_name}
    - name: dob
      type: gen
      processor:
        value: ${date}
        format: 2006-01-02

- table: account
  columns:
    - name: person_id
      type: each
      processor:
        table: person
        column: id
    - name: email
      type: gen
      processor:
        value: ${email}

- table: pet
  count: 1000
  columns:
    - name: id
      type: gen
      processor:
        value: ${uuid}
    - name: name
      type: gen
      processor:
        value: ${first_name}
    - name: "person_id"
      type: ref
      processor:
        table: person
        column: id