tables:
  # Create data for a person table.
  - table: person
    count: 10000
    columns:
      - name: id
        type: gen
        processor:
          value: ${uuid}

  # Create data for an event table.
  - table: event
    count: 100
    columns:
      - name: id
        type: gen
        processor:
          value: ${uuid}

  # Create data for a person_type table, with 5 rows.
  - table: person_type
    count: 5
    columns:
      - name: id
        type: gen
        processor:
          value: ${uuid}

      - name: name
        type: gen
        processor:
          value: TYPE-${uint16}
          format: "%05d"

  # Create data for a person_event many-to-many resolver table between
  # the person and event tables.
  - table: person_event
    columns:
      - name: person_id
        type: each
        processor:
          table: person
          column: id

      - name: event_id
        type: each
        processor:
          table: event
          column: id