- table: person
  count: 10
  columns:
    - name: id
      type: gen
      processor:
        value: ${uuid_hyphen}

- table: event
  count: 5
  columns:
    - name: id
      type: gen
      processor:
        value: ${uuid_hyphen}

- table: person_type
  count: 5
  columns:
    - name: id
      type: gen
      processor:
        value: ${uuid_hyphen}
    - name: name
      type: gen
      processor:
        value: ${int16}
        format: "%05d"

- table: person_event
  columns:
    - name: id
      type: gen
      processor:
        value: ${uuid_hyphen}
    - name: person_type
      type: ref
      processor:
        table: person_type
        column: id
    - name: person_id
      type: each
      processor:
        table: person
        column: id
    - name: event_id
      type: each
      processor:
        table: event
        column: id
    