tables:
  - name: one
    columns:
      - name: a
        type: const
        processor:
          values: [val_1, val_2, val_3]
      
      - name: b
        type: const
        processor:
          values: [val_1, val_2, val_3]