tables:
  - name: one
    columns:
      - name: c1
        type: const
        processor:
          values: [a, b, c]

  - name: two
    columns:
      - name: c1
        type: const
        processor:
          values: [a, b, c, d, e]
      
      - name: c2
        type: const
        processor:
          values: [a, b]
  
  - name: three
    columns:
      - name: c1
        type: const
        processor:
          values: [a, b]
      
      - name: c2
        type: const
        processor:
          values: [a, b, c, d, e]