tables:
  # Generate data for a person table, showing off a couple of column generators.
  - name: person
    count: 100000
    columns:
      - name: id
        type: gen
        processor:
          value: ${uuid}
      - name: full_name
        type: gen
        processor:
          value: ${name_prefix} ${first_name} ${last_name}
      - name: date_of_birth
        type: gen
        processor:
          value: ${date}
          format: 2006-01-02
      - name: user_type
        type: set
        processor:
          values: [admin, regular, read-only]
      - name: favourite_animal
        type: set
        processor:
          values: [rabbit, dog, cat]
          weights: [10, 60, 30]