# Generate data for a person table, showing off a couple of column generators.
- table: person
  count: 10
  columns:
    - name: full_name
      type: gen
      processor:
        value: ${name_prefix} ${first_name} ${last_name}
    - name: date_of_birth
      type: gen
      processor:
        value: ${date}
        format: 2006-01-02
    - name: username
      type: gen
      processor:
        value: ${username}
    - name: password
      type: gen
      processor:
        value: ${password}
    - name: last_updated
      type: gen
      processor:
        value: ${date}
        format: 2006-01-02T15:04:05
    - name: sku
      type: gen
      processor:
        value: SKU${uint16}
        format: "%05d"
    - name: set
      type: set
      processor:
        values: [admin, regular, read-only]