- table: person
  count: 10
  columns:
    - name: id
      type: gen
      processor:
        value: ${uuid_hyphen}
    - name: full_name
      type: gen
      processor:
        value: ${first_name} ${last_name}
    - name: date_of_birth
      type: gen
      processor:
        value: ${timestamp}
        format: Jan 2, 2006 at 3:04pm